const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const answerSchema = new Schema({
  poolname: { type: String, required: true },
  groupname: {type: String, required: false},
  username: { type: String, required: true },
  answer1: String,
  answer2: String,
  answer3: String,
  answer4: String,
  answer5: String,
  answer6: String,
  answer7: String,
  answer8: String,
  answer9: String,
  answer10: String,
  answer11: String,
  answer12: String,
  answer13: String,
  answer14: String,
  answer15: String,
  answer16: String,
  answer17: String,
  answer18: String,
  answer19: String,
  answer20: String,
  answer21: String,
  answer22: String,
  answer23: String,
  answer24: String,
  answer25: String,
  answer26: String,
  answer27: String,
  answer28: String,
  answer29: String,
  answer30: String,
  answer31: String,
  answer32: String,
  answer33: String,
  answer34: String,
  answer35: String,
  answer36: String,
  answer37: String,
  answer38: String,
  answer39: String,
  answer40: String,
  answer41: String,
  answer42: String,
  answer43: String,
  answer44: String,
  answer45: String,
  answer46: String,
  answer47: String,
  answer48: String,
  answer49: String,
  answer50: String,
  answer51: String,
  answer52: String,
  answer53: String,



  score: Number,
  date: { type: Date, default: Date.now }
});

const Answer = mongoose.model("Answer", answerSchema);

module.exports = Answer;
