const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const poolSchema = new Schema({
  name: { type: String, required: true },
  ask1: { type: String, required: true },
  option1a: { type: String, required: true },
  option1b: { type: String, required: true },
  answer1: String,
  ask2: { type: String, required: true },
  option2a: { type: String, required: true },
  option2b: { type: String, required: true },
  answer2: String,
  ask3: { type: String, required: true },
  option3a: { type: String, required: true },
  option3b: { type: String, required: true },
  answer3: String,
  ask4: { type: String, required: true },
  option4a: { type: String, required: true },
  option4b: { type: String, required: true },
  answer4: String,
  ask5: { type: String, required: true },
  option5a: { type: String, required: true },
  option5b: { type: String, required: true },
  answer5: String,
  ask6: { type: String, required: true },
  option6a: { type: String, required: true },
  option6b: { type: String, required: true },
  answer6: String,
  ask7: { type: String, required: true },
  option7a: { type: String, required: true },
  option7b: { type: String, required: true },
  answer7: String,
  ask8: { type: String, required: true },
  option8a: { type: String, required: true },
  option8b: { type: String, required: true },
  answer8: String,
  ask9: { type: String, required: true },
  option9a: { type: String, required: true },
  option9b: { type: String, required: true },
  answer9: String,
  ask10: { type: String, required: true },
  option10a: { type: String, required: true },
  option10b: { type: String, required: true },
  answer10: String,
  ask11: { type: String, required: true },
  option11a: { type: String, required: true },
  option11b: { type: String, required: true },
  answer11: String,
  ask12: { type: String, required: true },
  option12a: { type: String, required: true },
  option12b: { type: String, required: true },
  answer12: String,
  ask13: { type: String, required: true },
  option13a: { type: String, required: true },
  option13b: { type: String, required: true },
  answer13: String,
  ask14: { type: String, required: true },
  option14a: { type: String, required: true },
  option14b: { type: String, required: true },
  answer14: String,
  ask15: { type: String, required: true },
  option15a: { type: String, required: true },
  option15b: { type: String, required: true },
  answer15: String,
  ask16: { type: String, required: true },
  option16a: { type: String, required: true },
  option16b: { type: String, required: true },
  answer16: String,
  ask17: { type: String, required: true },
  option17a: { type: String, required: true },
  option17b: { type: String, required: true },
  answer17: String,
  ask18: { type: String, required: true },
  option18a: { type: String, required: true },
  option18b: { type: String, required: true },
  answer18: String,
  ask19: { type: String, required: true },
  option19a: { type: String, required: true },
  option19b: { type: String, required: true },
  answer19: String,
  ask20: { type: String, required: true },
  option20a: { type: String, required: true },
  option20b: { type: String, required: true },
  answer20: String,
  ask21: { type: String, required: true },
  option21a: { type: String, required: true },
  option21b: { type: String, required: true },
  answer21: String,
  ask22: { type: String, required: true },
  option22a: { type: String, required: true },
  option22b: { type: String, required: true },
  answer22: String,
  ask23: { type: String, required: true },
  option23a: { type: String, required: true },
  option23b: { type: String, required: true },
  answer23: String,
  ask24: { type: String, required: true },
  option24a: { type: String, required: true },
  option24b: { type: String, required: true },
  answer24: String,
  ask25: { type: String, required: true },
  option25a: { type: String, required: true },
  option25b: { type: String, required: true },
  answer25: String,
  ask26: { type: String, required: true },
  option26a: { type: String, required: true },
  option26b: { type: String, required: true },
  answer26: String,
  ask27: { type: String, required: true },
  option27a: { type: String, required: true },
  option27b: { type: String, required: true },
  answer27: String,
  ask28: { type: String, required: true },
  option28a: { type: String, required: true },
  option28b: { type: String, required: true },
  answer28: String,
  ask29: { type: String, required: true },
  option29a: { type: String, required: true },
  option29b: { type: String, required: true },
  answer29: String,
  ask30: { type: String, required: true },
  option30a: { type: String, required: true },
  option30b: { type: String, required: true },
  answer30: String,
  ask31: { type: String, required: true },
  option31a: { type: String, required: true },
  option31b: { type: String, required: true },
  answer31: String,
  ask32: { type: String, required: true },
  option32a: { type: String, required: true },
  option32b: { type: String, required: true },
  answer32: String,
  ask33: { type: String, required: true },
  option33a: { type: String, required: true },
  option33b: { type: String, required: true },
  answer33: String,
  ask34: { type: String, required: true },
  option34a: { type: String, required: true },
  option34b: { type: String, required: true },
  answer34: String,
  ask35: { type: String, required: true },
  option35a: { type: String, required: true },
  option35b: { type: String, required: true },
  answer35: String,
  ask36: { type: String, required: true },
  option36a: { type: String, required: true },
  option36b: { type: String, required: true },
  answer36: String,
  ask37: { type: String, required: true },
  option37a: { type: String, required: true },
  option37b: { type: String, required: true },
  answer37: String,
  ask38: { type: String, required: true },
  option38a: { type: String, required: true },
  option38b: { type: String, required: true },
  answer38: String,
  ask39: { type: String, required: true },
  option39a: { type: String, required: true },
  option39b: { type: String, required: true },
  answer39: String,
  ask40: { type: String, required: true },
  option40a: { type: String, required: true },
  option40b: { type: String, required: true },
  answer40: String,
  ask41: { type: String, required: true },
  option41a: { type: String, required: true },
  option41b: { type: String, required: true },
  answer41: String,
  ask42: { type: String, required: true },
  option42a: { type: String, required: true },
  option42b: { type: String, required: true },
  answer42: String,
  ask43: { type: String, required: true },
  option43a: { type: String, required: true },
  option43b: { type: String, required: true },
  answer43: String,
  ask44: { type: String, required: true },
  option44a: { type: String, required: true },
  option44b: { type: String, required: true },
  answer44: String,
  ask45: { type: String, required: true },
  option45a: { type: String, required: true },
  option45b: { type: String, required: true },
  answer45: String,
  ask46: { type: String, required: true },
  option46a: { type: String, required: true },
  option46b: { type: String, required: true },
  answer46: String,
  ask47: { type: String, required: true },
  option47a: { type: String, required: true },
  option47b: { type: String, required: true },
  answer47: String,
  ask48: { type: String, required: true },
  option48a: { type: String, required: true },
  option48b: { type: String, required: true },
  answer48: String,
  ask49: { type: String, required: true },
  option49a: { type: String, required: true },
  option49b: { type: String, required: true },
  answer49: String,
  ask50: { type: String, required: true },
  option50a: { type: String, required: true },
  option50b: { type: String, required: true },
  answer50: String,
  ask51: { type: String, required: true },
  option51a: { type: String, required: true },
  option51b: { type: String, required: true },
  answer51: String,
  ask52: { type: String, required: true },
  option52a: { type: String, required: true },
  option52b: { type: String, required: true },
  answer52: String,
  ask53: { type: String, required: true },
  option53a: { type: String, required: true },
  option53b: { type: String, required: true },
  answer53: String,











  date: { type: Date, default: Date.now }
});

const Pool = mongoose.model("Pool", poolSchema);

module.exports = Pool;
